### ISSUE TITLE
Sharing files makes bad request (nim 0.19.0, win64, gcc 6.3.0), I don't know why.

### ISSUE THREAD

**Issue by gekkonier** [dom96/jester#169] opened 2018-09-28 21:50 UTC
Hello!
I have this:
gcc (x86_64-win32-seh-rev1, Built by MinGW-W64 project) 6.3.0 as suggested,
Nim Compiler Version 0.19.0 [Windows: amd64]

I installed jester via nimble. Normal stuff like serving text works like a charm. But sharing files do not.
I'm not able to get public folder to work. I'm not sure if it's my fail and hope you don't roast me to much ;-)
Here is a log if that of any help:
```
C:\Users\x\Desktop\webtest>nim -v
Nim Compiler Version 0.19.0 [Windows: amd64]
Compiled at 2018-09-26
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: f6c5c636bb1a1f4e1301ae0ba5a8afecef439132
active boot switches: -d:release

C:\Users\x\Desktop\webtest>tree /f
Auflistung der Ordnerpfade
Volumeseriennummer : CE7F-6DCD
C:.
│   hello.exe
│   hello.nim
│
└───public
    │   hm.html
    │
    └───movie
            DVD571_05.mp4


C:\Users\x\Desktop\webtest>type hello.nim
import htmlgen
import jester

routes:
  get "/":
    resp h1("hello world")
  get "/test":
    resp a(href="movie/DVD571_05.mp4", "gogo")
  get "/test2":
    resp a(href="hm.html", "click for hm")
Then, if I try to > http://localhost:5000/movie/DVD571_05.mp4 or http://localhost:5000/hm.html I get:

C:\Users\x\Desktop\webtest>hello
INFO Jester is making jokes at http://127.0.0.1:5000 (all interfaces)
DEBUG GET /hm.html
DEBUG   400 Bad Request {"content-type": @["text/html;charset=utf-8"]}
DEBUG GET /favicon.ico
DEBUG   400 Bad Request {"content-type": @["text/html;charset=utf-8"]}
DEBUG GET /movie/DVD571_05.mp4
DEBUG   400 Bad Request {"content-type": @["text/html;charset=utf-8"]}
DEBUG GET /favicon.ico
DEBUG   400 Bad Request {"content-type": @["text/html;charset=utf-8"]}
```

**Comment by dom96** [comment] 2018-09-28 21:59
Duplicate of https://github.com/dom96/jester/issues/152 I think.

If you could debug this and create a PR I'd really appreciate it (I don't have a Windows machine handy).

**Closed by dom96** 2018-09-28 21:59 UTC
