### ISSUE TITLE
Async procedure (processRequest) yielded `nil`

### ISSUE THREAD

**Issue by shawnye** [dom96/jester#179] opened 2018-11-18 12:54 UTC
nim - 0.19.0  
jester - 0.4.1

<pre>
import jester

routes:  #line 15
  get "/":
    resp "index"

</pre>

nothing else ,when `nimble build` and run , access `http://localhost:5000/`, it was ok just for once.
but errors occured:
<pre>
INFO Jester is making jokes at http://127.0.0.1:5000 (all interfaces)
DEBUG GET /
DEBUG   200 OK {"content-type": @["text/html;charset=utf-8"]}
tinyweb.nim(15)          tinyweb
jester.nim(489)          serve
asyncdispatch.nim(1649)  runForever
asyncdispatch.nim(1514)  poll
asyncdispatch.nim(353)   runOnce
asyncdispatch.nim(189)   processPendingCallbacks
asyncmacro.nim(47)       processRequest_continue
[[reraised from:
tinyweb.nim(15)          tinyweb
jester.nim(489)          serve
asyncdispatch.nim(1649)  runForever
asyncdispatch.nim(1514)  poll
asyncdispatch.nim(353)   runOnce
asyncdispatch.nim(189)   processPendingCallbacks
asyncmacro.nim(36)       processClient_continue
asynchttpserver.nim(288) processClientIter
asyncfutures.nim(302)    read
]]
[[reraised from:
tinyweb.nim(15)          tinyweb
jester.nim(489)          serve
asyncdispatch.nim(1649)  runForever
asyncdispatch.nim(1514)  poll
asyncdispatch.nim(353)   runOnce
asyncdispatch.nim(189)   processPendingCallbacks
asyncfutures.nim(348)    :anonymous
]]
Error: unhandled exception: Async procedure (processRequest) yielded `nil`, are you await'ing a `nil` Future?
Async traceback:
  tinyweb.nim(15)          tinyweb
  jester.nim(489)          serve
  asyncdispatch.nim(1649)  runForever
  asyncdispatch.nim(1514)  poll
    ## Processes asynchronous completion events
  asyncdispatch.nim(353)   runOnce
  asyncdispatch.nim(189)   processPendingCallbacks
    ## Executes pending callbacks
  asyncmacro.nim(47)       processRequest_continue
    ## Resumes an async procedure
  #[
    tinyweb.nim(15)          tinyweb
    jester.nim(489)          serve
    asyncdispatch.nim(1649)  runForever
    asyncdispatch.nim(1514)  poll
      ## Processes asynchronous completion events
    asyncdispatch.nim(353)   runOnce
    asyncdispatch.nim(189)   processPendingCallbacks
      ## Executes pending callbacks
    asyncmacro.nim(36)       processClient_continue
      ## Resumes an async procedure
    asynchttpserver.nim(288) processClientIter
    asyncfutures.nim(302)    read
  ]#
Exception message: Async procedure (processRequest) yielded `nil`, are you await'ing a `nil` Future?
Exception type: [AssertionError]
</pre>

**Comment by dom96** [comment] 2018-11-20 00:17
OS?

Also, try ``nimble install httpbeast@#head``.

**Comment by shawnye** [comment] 2018-11-21 06:18
OS: Windows 7 64bit
I'll try `httpbeast` later.

**Comment by dom96** [comment] 2018-11-21 23:08
oh, if you're on Windows then this isn't even a httpbeast problem.

This is a duplicate of #165

**Closed by dom96** 2018-11-21 23:08 UTC

**Comment by shawnye** [comment] 2018-11-27 01:18
Updated source to nim 0.19.9 , the problem is solved.

**Comment by dom96** [comment] 2018-11-27 22:37
oh really? Interesting, so it's a Nim regression.
