### ISSUE TITLE
Simple hello world fails on windows

### ISSUE THREAD

**Issue by GULPF** [dom96/jester#183] opened 2019-01-12 16:43 UTC
This simple hello world program crashes on the first request on Windows 10 (Nim devel):
```nim
import jester

routes:
  get "/":
    resp "Hello, World!"
```
Stacktrace:
```
asyncdispatch.nim(1858)  runForever
asyncdispatch.nim(1514)  poll
asyncdispatch.nim(354)   runOnce
asyncdispatch.nim(192)   processPendingCallbacks
asyncmacro.nim(36)       serve_continue
asynchttpserver.nim(315) serveIter
asyncmacro.nim(307)      processClient
asyncmacro.nim(36)       processClient_continue
asynchttpserver.nim(291) processClientIter
asyncmacro.nim(307)      processRequest
asyncmacro.nim(47)       processRequest_continue
[[reraised from:
repro.nim(11)            repro
jester.nim(489)          serve
asyncdispatch.nim(1858)  runForever
asyncdispatch.nim(1514)  poll
asyncdispatch.nim(354)   runOnce
asyncdispatch.nim(192)   processPendingCallbacks
asyncmacro.nim(36)       serve_continue
asynchttpserver.nim(315) serveIter
asyncmacro.nim(307)      processClient
asyncmacro.nim(39)       processClient_continue
asynchttpserver.nim(291) processClientIter
asyncfutures.nim(308)    read
]]
[[reraised from:
repro.nim(11)            repro
jester.nim(489)          serve
asyncdispatch.nim(1858)  runForever
asyncdispatch.nim(1514)  poll
asyncdispatch.nim(354)   runOnce
asyncdispatch.nim(192)   processPendingCallbacks
asyncfutures.nim(355)    :anonymous
]]
Error: unhandled exception: Async procedure (processRequest) yielded `nil`, are you await'ing a `nil` Future?
Async traceback:
  repro.nim(11)            repro
  jester.nim(489)          serve
  asyncdispatch.nim(1858)  runForever
  asyncdispatch.nim(1514)  poll
    ## Processes asynchronous completion events
  asyncdispatch.nim(354)   runOnce
  asyncdispatch.nim(192)   processPendingCallbacks
    ## Executes pending callbacks
  asyncmacro.nim(36)       serve_continue
    ## Resumes an async procedure
  asynchttpserver.nim(315) serveIter
  asyncmacro.nim(307)      processClient
  asyncmacro.nim(36)       processClient_continue
    ## Resumes an async procedure
  asynchttpserver.nim(291) processClientIter
  asyncmacro.nim(307)      processRequest
  asyncmacro.nim(47)       processRequest_continue
    ## Resumes an async procedure
  #[
    repro.nim(11)            repro
    jester.nim(489)          serve
    asyncdispatch.nim(1858)  runForever
    asyncdispatch.nim(1514)  poll
      ## Processes asynchronous completion events
    asyncdispatch.nim(354)   runOnce
    asyncdispatch.nim(192)   processPendingCallbacks
      ## Executes pending callbacks
    asyncmacro.nim(36)       serve_continue
      ## Resumes an async procedure
    asynchttpserver.nim(315) serveIter
    asyncmacro.nim(307)      processClient
    asyncmacro.nim(39)       processClient_continue
      ## Resumes an async procedure
    asynchttpserver.nim(291) processClientIter
    asyncfutures.nim(308)    read
  ]#
Exception message: Async procedure (processRequest) yielded `nil`, are you await'ing a `nil` Future?
Exception type: [AssertionError]
```

**Comment by dom96** [comment] 2019-01-12 20:49
Duplicate of #165

**Closed by dom96** 2019-01-12 20:49 UTC
