### ISSUE TITLE
Providing nil as a value to template resp*(...): typed, will crash jester 

### ISSUE THREAD

**Issue by zacharycarter** [dom96/jester#133] opened 2018-02-09 02:58 UTC
Steps to reproduce:

1) Create a route like this:

```nim
routes:
  get "/bug":
    resp(nil)
```

Send a http request to the endpoint - jester crashes.

I believe the problem is somewhere in this function -
https://github.com/dom96/jester/blob/master/jester.nim#L87-L94

Nim version info:
```
Nim Compiler Version 0.17.3 [MacOSX: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 70e8640244e48e8d62c5af42101c9df2b57224d9
active boot switches: -d:release
```

**Comment by dom96** [comment] 2018-05-26 13:14
Duplicate of #139.

**Closed by dom96** 2018-05-26 13:14 UTC
